;;; go-stacktracer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-stacktracer.el

(autoload 'go-stacktracer-region "go-stacktracer" "\
Parse a Go stacktrace from START to END.

(fn START END)" t)
(register-definition-prefixes "go-stacktracer" '("go-stacktracer-"))

;;; End of scraped data

(provide 'go-stacktracer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-stacktracer-autoloads.el ends here
