;;; flymake-go-staticcheck-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-go-staticcheck.el

(autoload 'flymake-go-staticcheck-checker "flymake-go-staticcheck" "\
Run go-staticcheck on the current buffer.
Report results using FLYMAKE-REPORT-FN.  All other parameters are currently IGNORED.

(fn FLYMAKE-REPORT-FN &rest IGNORED)")
(autoload 'flymake-go-staticcheck-enable "flymake-go-staticcheck" "\
Add flymake-go-staticcheck as a buffer-local Flymake backend." t)
(autoload 'flymake-go-staticcheck-disable "flymake-go-staticcheck" "\
Remove flymake-go-staticcheck from Flymake backends." t)
(register-definition-prefixes "flymake-go-staticcheck" '("flymake-go-staticcheck-"))

;;; End of scraped data

(provide 'flymake-go-staticcheck-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-go-staticcheck-autoloads.el ends here
