;;; go-complete-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-complete.el

(autoload 'go-complete-at-point "go-complete" "\
Complete go expression at point." t)
(register-definition-prefixes "go-complete" '("go-complete-"))

;;; End of scraped data

(provide 'go-complete-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-complete-autoloads.el ends here
