;;; go-scratch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-scratch.el

(autoload 'go-scratch "go-scratch" "\
Go to the Go scratch buffer." t)
(register-definition-prefixes "go-scratch" '("go-scratch-"))

;;; End of scraped data

(provide 'go-scratch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-scratch-autoloads.el ends here
