;;; go-add-tags-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-add-tags.el

(autoload 'go-add-tags "go-add-tags" "\
Add field tags for struct fields.

(fn TAGS BEGIN END CONV-FN)" t)
(register-definition-prefixes "go-add-tags" '("go-add-tags-"))

;;; End of scraped data

(provide 'go-add-tags-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-add-tags-autoloads.el ends here
