;;; go-expr-completion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-expr-completion.el

(autoload 'go-expr-completion "go-expr-completion" "\
Invoke `go-expr-completion'." t)
(register-definition-prefixes "go-expr-completion" '("go-expr-completion--"))

;;; End of scraped data

(provide 'go-expr-completion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-expr-completion-autoloads.el ends here
