;;; oberon-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from oberon.el

(autoload 'oberon-mode "oberon" "\
Major mode for editing Oberon/Oberon-2 program texts.

Key bindings:

\\{oberon-mode-map}" t)
(register-definition-prefixes "oberon" '("oberon-" "obn-"))

;;; End of scraped data

(provide 'oberon-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; oberon-autoloads.el ends here
